  spring:
    application:
      name: internet-banking-account-opening-service


  server:
    port: 8084

  spring-doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html